name: Build EXE and Upload to Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. Install dependencies
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      # 4. Build EXE with PyInstaller (optimized)
      - name: Build executable
        run: |
          set PYTHONOPTIMIZE=1 && pyinstaller --onefile --clean --name unified_diff_patcher --console --noupx unified_diff_patcher.py
        shell: cmd

      # 5. Debug: List output files
      - name: List build output
        run: |
          dir
          dir dist
          dir build
        shell: cmd

      # 6. Install UPX for compression
      - name: Install UPX
        run: |
          choco install upx --no-progress

      # 7. Compress EXE with UPX (forced)
      - name: Compress EXE with UPX
        run: |
          upx --force --best --lzma dist\unified_diff_patcher.exe

      # 8. Upload EXE to GitHub Release
      - name: Upload EXE to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/unified_diff_patcher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
